config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'

  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates :name, :presence => true
  validates :cost, :presence => true
  validates :origin, :presence => true

  scope :most_recent, -> { order(created_at: :desc).limit(3) }

  scope :most_reviewed, -> {(
    select("products.name, products.cost, products.origin, products.id, products.created_at, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    )}

  scope :local, -> { where(origin: 'USA')}
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  validates :author, :presence => true
  validates :content, :presence => true, length: {minimum: 2, maximum: 250}
  validates :rating, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @recent_products = Product.most_recent
    # index of 0, incase there are matching review counts
    @most_reviewed = Product.most_reviewed[0]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params['filter'] === 'local'
      @products = Product.local
    else
      @products = Product.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to  products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    flash[:alert] = "#{@product.name} has been deleted"
    @product.destroy
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :cost, :origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.rating = @review.rating.to_i
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    @review.destroy
    flash[:alert] = "Review has been deleted"
    redirect_to product_path(@review.product)
  end


private
  def review_params
    params.require(:review).permit(:author, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<header class="sans-serif">
  <div class="cover bg-left bg-center-l" style="background-image: url(http://www.commonground.coop/sites/default/files/vegetables%20wooden%20background-croppedx2.jpg)">
    <div class="landing-shade bg-black-80 pb5 pb6-m pb7-l">
      <nav class="dt w-100 mw8 center">

      </nav>
      <div class="tc-l mt4 mt5-m mt6-l ph3">
        <h1 class="f2 f1-l fw2 white-90 mb0 lh-title">All your dietary needs in one place</h1>
        <h2 class="fw1 f3 white-80 mt3 mb4">Global food distribution, at the click of a button</h2>
        <%= link_to "View Products", products_path, class: "f6 no-underline grow dib v-mid bg-blue white ba b--blue ph3 pv2 mb3" %>
        <span class="dib v-mid ph3 white-70 mb3">or</span>
        <%= link_to "Shop Local", {:controller => "products", :action => "index", :filter => "local" }, class: "f6 no-underline grow dib v-mid white ba b--white ph3 pv2 mb3" %>

        <article class="cf">
          <div class="fl w-50  tc">
            <h3 class="center white">Most Reviewed:</h3>
            <%= link_to @most_reviewed.name, product_path(@most_reviewed), class: "f4 fw7 dib pa2 no-underline bg-animate white hover-bg-light-blue black" %>
          </div>
          <div class="fl w-50  tc">
            <h3 class="center white">Recently added products:</h3>
            <% @recent_products.each do |product| %>
              <%= link_to product.name, product_path(product), class: "f4 fw7 dib pa2 no-underline bg-animate white hover-bg-light-blue black" %>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
    <% object.errors.full_messages.each do |message| %>
      <p>
        <%= flash[:alert] = message %>
      </p>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperMarioFood</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/tachyons/css/tachyons.min.css">
  </head>

  <body>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<div class="marginize">
  <h2>Edit <%= @product.name %></h2>

  <%= render "form" %>
</div>

app/views/products/index.html.erb
<div class="marginize">
  <p>
    <%= link_to "Home", root_path, class: "f4 fw7 dib pa2 no-underline bg-animate hover-bg-light-blue blue" %>
  </p>

  <h1>Products</h1>

  <%= link_to "New Product", new_product_path, class: "f4 fw7 dib pa2 no-underline bg-animate  hover-bg-light-blue blue" %>

  <% @products.each do |product| %>
  <div class="pa1 lh-copy">
    <span class="f4 fw7 dib  no-underline bg-animate bg-white hover-bg-light-blue "><%= link_to product.name, product_path(product), class: "f4 fw7 dib  no-underline bg-animate  hover-bg-light-blue blue"%></span> | <%= "Origin: #{product.origin}" %> | $<%= product.cost %>
  </div>
  <% end %>

  <% if !params[:filter] %>
  <%= will_paginate @products %>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="marginize">
  <h1>New Product</h1>

  <%= render "form" %>
</div>

app/views/products/show.html.erb
<div class="marginize">
  <p>
    <%= link_to "Home", root_path, class: "f4 fw7 dib pa2 no-underline bg-animate  hover-bg-light-blue blue" %>
  </p>

  <h1><%= @product.name %></h1>
  <h3>located in: <%= @product.origin %></h3>
  <h3>$<%= @product.cost %></h3>

  <% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <ul>
    <% @product.reviews.each do |review| %>
    <li>
      by: <%= review.author %> | <%= review.content %> | Rating: <%= review.rating %>
      <%= link_to "Edit", edit_product_review_path(@product, review), class: "f4 fw7 dib pa2 no-underline bg-animate  hover-bg-light-blue blue" %> |
      <%= link_to "Delete", product_review_path(@product, review),
      :data => {:confirm => "Are you sure?",
        :method => "delete"} , class: "f4 fw7 dib pa2 no-underline bg-animate  hover-bg-light-blue blue"%>
      </li>
      <% end %>
    </ul>
    <% else %>
    <p>There are no reviews yet!</p>
    <% end %>

    <p><%= link_to "Add a review", new_product_review_path(@product), class: "f4 fw7 dib pa2 no-underline bg-animate  hover-bg-light-blue blue" %></p>
      <p><%= link_to "Return to products", products_path , class: "f4 fw7 dib pa2 no-underline bg-animate  hover-bg-light-blue blue"%></p>
      <br>
      <p><%= link_to "Edit Product", edit_product_path(@product), class: "f4 fw7 dib pa2 no-underline bg-animate  hover-bg-light-blue blue" %></p>
      <p><%= link_to "Delete Product", product_path(@product),
      :data => {:confirm => "You sure?",
        :method => "delete"}, class: "f4 fw7 dib pa2 no-underline bg-animate  hover-bg-light-blue blue" %></p>
</div>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  1<%= f.radio_button :rating, '1' %>
  2<%= f.radio_button :rating, '2' %>
  3<%= f.radio_button :rating, '3' %>
  4<%= f.radio_button :rating, '4' %>
  5<%= f.radio_button :rating, '5' %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/edit.html.erb
<h2>Edit Review <%= @review.content %></h2>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @product.name %></h1>

<%= render 'form' %>